backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Imagen previa al blog", name: "featuredimage", widget: image}
      - {label: "Texto alternativo", name: altFeatured, widget: string}
      - {label: "Resumen previo al blog", name: "description", widget: "text"}
      - {label: "Titulo del blog", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Autor", name: "author", widget: "object", fields: [{label: "Nombre", name: "name", widget: "string"}, {label: "Foto del autor", name: "photo", widget: image}, {label: "Texto alternativo", name: alt, widget: string}]}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Imagen de portada (imagen mostrada en detalle del blog)", name: "coverImage", widget: image}
      - {label: "Texto alternativo", name: altCover, widget: string}
      - {label: "Imagen a mostrar en la página de blog", name: "listImage", widget: image}
      - {label: "Texto alternativo", name: altList, widget: string}
      - {label: "Contenido", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
    
  - name: "circular"
    label: "Circulares"
    folder: "src/pages/circular"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "circular-post"}
      - {label: "Resumen previo al circular", name: "description", widget: "text"}
      - {label: "Titulo del circular", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Autor", name: "author", widget: "object", fields: [{label: "Nombre", name: "name", widget: "string"}, {label: "Foto del autor", name: "photo", widget: image}, {label: "Texto alternativo", name: alt, widget: string}]}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Imagen de portada (imagen mostrada en detalle del circular)", name: "coverImage", widget: image}
      - {label: "Texto alternativo", name: altCover, widget: string}
      - {label: "Imagen a mostrar en la página de circular", name: "listImage", widget: image}
      - {label: "Texto alternativo", name: altList, widget: string}
      - {label: "Contenido", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  
  - name: "procedure"
    label: "Procedimiento"
    folder: "src/pages/procedure"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "procedure-post"}
      - {label: "Título", name: title, widget: string}
      - {label: "Imagen thumbnail", name: "thumbnail", widget: "object", fields: [{label: "Imagen", name: image, widget: image}, {label: "Texto alternativo", name: alt, widget: string}]}
      - {label: "Imagen de portada", name: "cover", widget: "object", fields: [{label: "Imagen", name: image, widget: image}, {label: "Texto alternativo", name: alt, widget: string}]}
      - {label: "Procedimientos", name: "procedures", widget: list, fields: [{label: "Nombre", name: name, widget: string}, {label: "Imagen", name: image, widget: image}, {label: "Texto alternativo", name: alt, widget: string}, {label: "Descripción", name: "description", widget: "text"}]}
    
  - name: "educativeOffers"
    label: "Ofertas educativas"
    folder: "src/pages/educative"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "educative-post"}
      - {label: "Título", name: title, widget: string}
      - {label: "Descripción breve", name: resume, widget: text}
      - {label: "Imagen", name: "thumbnail", widget: "object", fields: [{label: "Imagen", name: image, widget: image}, {label: "Texto alternativo", name: alt, widget: string}]}

  - name: "product"
    label: "Productos"
    folder: "src/pages/product"
    create: true
    identifier_field: name
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
      - {label: "Nombre", name: name, widget: string}
      - {label: "Imagen del producto", name: "cover", widget: object, fields: [{label: "Imagen de la página principal", name: image, widget: image}, {label: "Texto alternativo a la imagen principal", name: alt, widget: string}, {label: "Imagen para página de productos", name: imageProd, widget: image}, {label: "Texto alternativo para imagen de página de productos", name: altProd, widget: string}]}
      - {label: "Productos", name: "prod", widget: list, fields: [{label: "Nombre", name: name, widget: string}, {label: "Imagen", name: image, widget: image}, {label: "Texto alternativo", name: alt, widget: string}, {label: "Precio", name: "price", widget: string}]}

  - name: "pages"
    label: "Páginas"
    files:
      - file: "src/pages/index.md"
        label: "Página principal"
        name: "landing"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "landing"}
          - {label: "Título del banner principal", name: "bannerTitle", widget: "string"}
          - {label: "Descripción del banner principal", name: "bannerDescription", widget: "string"}
          - {label: "Lista de características mostradas en banner", name: "charList", widget: list, fields: [{label: "Imagen", name: "charImage", widget: "object", fields: [{label: "Imagen", name: "image", widget: image}, {label: "Texto alternativo a la imagen", name: alt, widget: string}]}, {label: "Nombre", name: name, widget: string}, {label: "Descripción breve", name: description, widget: text}]}
          - {label: "Video", name: "video", widget: file}
          - {label: "Datos de contactos", name: "contacts", widget: "object", fields: [{label: "Dirección", name: "address", widget: "text"},{label: "Teléfonos", name: "phones", widget: "list", fields: [{label: "Teléfono", name: "phone", widget: "string"}]}, {label: "Correo electrónico", name: "email", widget: "string"}]}
          - {label: "Redes sociales", name: networks, widget: object, fields: [{label: "Url de twitter", name: twitter, widget: string}, {label: "Url de instagram", name: instagram, widget: string}, {label: "Url de youtube", name: youtube, widget: string}, {label: "Url de facebook", name: facebook, widget: string}]}
      - file: "src/pages/profile/index.md"
        label: "Página de perfil"
        name: "profile"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "profile"}
          - {label: "Nombre a mostrar", name: name, widget: string}
          - {label: "Imagen grande", name: image, widget: image}
          - {label: "Texto alternativo a la imagen grande", name: alt, widget: string}
          - {label: "Imagen pequeña", name: imageMobile, widget: image}
          - {label: "Texto alternativo a la imagen pequeña", name: altMobile, widget: string}
          - {label: "Descripción", name: description, widget: "markdown"}
          - {label: "Redes sociales", name: networks, widget: object, fields: [{label: "Wathsapp", name: wathsapp, widget: string}, {label: "Url de instagram", name: instagram, widget: string}, {label: "Url de youtube", name: youtube, widget: string}, {label: "Url de facebook", name: facebook, widget: string}]}
      - file: "src/pages/admission/index.md"
        label: "Página de admisión"
        name: "admission"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "admission"}
          - {label: "Sección de admisión", name: section1, widget: object, fields: [{label: "Descripción", name: description, widget: "markdown"}, {label: "Ejes", name: ejes, widget: list, fields: [{title: "Título", name: title, widget: string}]}, {label: "Imagen", name: image, widget: object, fields: [{label: "Imagen", name: image, widget: image}, {label: "Texto alternativo", name: alt, widget: string}]}]}
          - {label: "Sección de datos del colegio", name: section2, widget: object, fields: [{label: "Imagen", name: image, widget: object, fields: [{label: "Imagen", name: image, widget: image}, {label: "Texto alternativo", name: alt, widget: string}]}, {label: "Items", name: items, widget: list, fields: [{label: "Título", name: title, widget: "string"}, {label: "Descripción", name: description, widget: "text", required: false}, {label: "Viñetas", name: lst, required: false, widget: list, fields: [{label: "Título", name: title, widget: string}]}]}]}
          - {label: "Sección de oferta educativa", name: section3, widget: object, fields: [{label: "Título", name: title, widget: string}, {label: "Imagen", name: image, widget: object, fields: [{label: "Imagen", name: image, widget: image}, {label: "Texto alternativo", name: alt, widget: string}]}, {label: "Items", name: items, widget: list, fields: [{label: "Título", name: title, widget: "string"}, {label: "Descripción", name: description, widget: "text", required: false}, {label: "Viñetas", name: lst, required: false, widget: list, fields: [{label: "Título", name: title, widget: string}]}]}]}
          - {label: "Sección proceso de admisión", name: section4, widget: object, fields: [{label: "Pasos", name: steps, widget: list, fields: [{label: "Imagen", name: numImage, widget: object, fields: [{label: "Imagen", name: image, widget: image}, {label: "Texto alternativo", name: alt, widget: string}]}, {label: "Descripción", name: description, widget: "markdown"}]}]}
          - {label: "Sección proceso de matrícula", name: section5, widget: object, fields: [{label: "Pasos", name: steps, widget: list, fields: [{label: "Imagen", name: numImage, widget: object, fields: [{label: "Imagen", name: image, widget: image}, {label: "Texto alternativo", name: alt, widget: string}]}, {label: "Descripción", name: description, widget: "markdown"}]}]}
          - {label: "Sección costos educativos", name: section6, widget: object, fields: [{label: "Costos", name: "costs", widget: list, fields: [{label: "Imagen", name: image, widget: object, fields: [{label: "Imagen", name: image, widget: image}, {label: "Texto alternativo", name: alt, widget: string}]}, {label: "Título", name: title, widget: string}]}]}
          - {label: "Sección documentos económicos", name: section7, widget: object, fields: [{label: "Documentos de admisión", name: admission, widget: object, fields: [{label: "Imagen", name: image, widget: object, fields: [{label: "Imagen", name: image, widget: image}, {label: "Texto alternativo", name: alt, widget: string}]}, {label: "Título del botón", name: title, widget: string}, {label: "Contenido", name: content, widget: "markdown"}]}, {label: "Documentos de matrícula", name: matri, widget: object, fields: [{label: "Imagen", name: image, widget: object, fields: [{label: "Imagen", name: image, widget: image}, {label: "Texto alternativo", name: alt, widget: string}]}, {label: "Título del botón", name: title, widget: string}, {label: "Contenido", name: content, widget: "markdown"}]}, {label: "Nota", name: notes, widget: text}]}
      - file: "src/pages/about-us/index.md"
        label: "Página de nosotros"
        name: "about-us"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "admission"}
          - {label: "Sección 1", name: section1, widget: object, fields: [{label: "Descripción", name: description, widget: "markdown"}, {label: "Imagen", name: image, widget: object, fields: [{label: "Imagen", name: image, widget: image}, {label: "Texto alternativo", name: alt, widget: string}]}]}
          - {label: "Sección 2", name: section2, widget: object, fields: [{label: "Título", name: title, widget: string}, {label: "Descripción 1", name: description1, widget: "markdown"}, {label: "Imagen 1", name: image1, widget: object, fields: [{label: "Imagen", name: image, widget: image}, {label: "Texto alternativo", name: alt, widget: string}]}, {label: "Descripción 2", name: description2, widget: "markdown"}, {label: "Imagen 2", name: image2, widget: object, fields: [{label: "Imagen", name: image, widget: image}, {label: "Texto alternativo", name: alt, widget: string}]}]}
          - {label: "Sección 3", name: section3, widget: object, fields: [{label: "Imagen", name: image, widget: object, fields: [{label: "Imagen", name: image, widget: image}, {label: "Texto alternativo", name: alt, widget: string}]}, {label: "Título párrafo 1", name: title1, widget: string}, {label: "Párrafo 1", name: description1, widget: "markdown"}, {label: "Título párrafo 2", name: title2, widget: string}, {label: "Subtítulo párrafo 2", name: subtitle, widget: string}, {label: "Párrafo 2", name: description2, widget: "markdown"}, {label: "Lista de características", name: "items", widget: list, fields: [{label: "Título", name: title, widget: string}, {label: "Descripción", name: description, widget: "markdown"}, {label: "Imagen", name: image, widget: object, fields: [{label: "Imagen", name: image, widget: image}, {label: "Texto alternativo", name: alt, widget: string}]}]}]}
          - {label: "Section 4", name: section4, widget: object, fields: [{label: "Título", name: title, widget: string}, {label: "Otra lista de características", name: "items", widget: list, fields: [{label: "Título", name: title, widget: string}, {label: "Imagen", name: image, widget: object, fields: [{label: "Imagen", name: image, widget: image}, {label: "Texto alternativo", name: alt, widget: string}]}]}]}
          - {label: "Section 5", name: section5, widget: object, fields: [{label: "Imagen", name: image, widget: object, fields: [{label: "Imagen", name: image, widget: image}, {label: "Texto alternativo", name: alt, widget: string}]}, {label: "Columna 1", name: description1, widget: "markdown"}, {label: "Columna 2", name: description2, widget: "markdown"}]}
      # - file: "src/pages/about/index.md"
      #   label: "About"
      #   name: "about"
      #   fields:
      #     - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
      #     - {label: "Title", name: "title", widget: "string"}
      #     - {label: "Body", name: "body", widget: "markdown"}
      # - file: "src/pages/products/index.md"
      #   label: "Products Page"
      #   name: "products"
      #   fields:
      #     - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
      #     - {label: Title, name: title, widget: string}
      #     - {label: Image, name: image, widget: image}
      #     - {label: Heading, name: heading, widget: string}
      #     - {label: Description, name: description, widget: string}
      #     - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
      #     - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      #     - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
      #     - {label: Full_image, name: full_image, widget: image}
      #     - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
